# Regenerates the data/*.js files that deck.html renders figures from.
#
#     julia data/generate.jl
#
# The deck loads these with <script src="data/....js"> instead of fetch(),
# so the slides work when opened straight from file:// — no web server needed.
# Swap the toy numbers below for real measurements (or compute them here).

datadir = @__DIR__

jsnum(x::Real) = isinteger(x) ? string(Int(x)) : string(x)
jslist(xs) = "[" * join(jsnum.(xs), ", ") * "]"
jsstrlist(xs) = "[" * join("\"" .* xs .* "\"", ", ") * "]"

function write_js(file, key, body)
    open(joinpath(datadir, file), "w") do io
        println(io, "// Generated by data/generate.jl — do not edit by hand.")
        println(io, "window.DECK_DATA = window.DECK_DATA || {};")
        println(io, "window.DECK_DATA.", key, " = ", body, ";")
    end
    return @info "wrote $file"
end

# ---- grouped bar chart (renders into #oplegend / #opchart) ------------------
ops = [
    ("parse", 12.4, 8.1),
    ("solve", 31.0, 14.2),
    ("assemble", 22.7, 21.5),
    ("write", 9.3, 9.0),
]

rows = join(
    ("  { \"op\": \"$op\", \"vals\": $(jslist((a, b))) }" for (op, a, b) in ops),
    ",\n"
)

write_js(
    "ops.js", "ops", """
    {
      "series": $(jsstrlist(["before", "after"])),
      "colors": $(jsstrlist(["fd8", "hh"])),
      "unit": "ms",
      "rows": [
    $rows
      ]
    }"""
)

# ---- log–log scaling chart (renders into #scalelegend / #scalechart) --------
# series[1] is treated as the slower baseline for the gap annotation.
n = [2, 4, 8, 16, 32, 64, 128, 256]
slow = [0.06, 0.23, 0.89, 6.1, 41.4, 293.0, 2090.0, 16190.0]
fast = [0.03, 0.06, 0.23, 1.6, 8.1, 49.6, 344.0, 2570.0]

write_js(
    "scaling.js", "scaling", """
    {
      "title": "example scaling",
      "n": $(jslist(n)),
      "unit": "us",
      "series": [
        { "name": "baseline", "color": "fd8", "us": $(jslist(slow)) },
        { "name": "optimized", "color": "hh", "us": $(jslist(fast)) }
      ]
    }"""
)
